name: Build LiveDelay Plugin

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
    - name: Checkout plugin code
      uses: actions/checkout@v3
      with:
        path: plugin

    - name: Checkout OBS Studio
      uses: actions/checkout@v3
      with:
        repository: obsproject/obs-studio
        ref: '30.0.0'
        path: obs-studio
        submodules: recursive

    - name: Setup Qt
      uses: jurplel/install-qt-action@v3
      with:
        version: '6.5.0'
        arch: 'win64_msvc2019_64'

    - name: Setup MSVC
      uses: microsoft/setup-msbuild@v1.1

    - name: Download OBS Dependencies
      run: |
        $ErrorActionPreference = "Stop"
        $depsVersion = "2023-11-03"
        $depsUrl = "https://github.com/obsproject/obs-deps/releases/download/$depsVersion/windows-deps-$depsVersion-x64.zip"
        Invoke-WebRequest -Uri $depsUrl -OutFile "obs-deps.zip"
        Expand-Archive -Path "obs-deps.zip" -DestinationPath "${{github.workspace}}/obs-deps"
      shell: pwsh

    - name: Configure OBS Studio
      run: |
        cd obs-studio
        mkdir build
        cd build
        cmake -G "Visual Studio 17 2022" -A x64 -DCMAKE_PREFIX_PATH="${{github.workspace}}/obs-deps;${{github.workspace}}/obs-deps/bin" -DENABLE_BROWSER=OFF -DENABLE_WEBSOCKET=OFF ..

    - name: Build OBS Studio
      run: |
        cd obs-studio/build
        cmake --build . --config RelWithDebInfo --target libobs
        cmake --build . --config RelWithDebInfo --target obs-frontend-api

    - name: Configure LiveDelay Plugin
      run: |
        $obsPath = "${{github.workspace}}\obs-studio"
        Write-Host "OBS Source Directory: $obsPath"
        if (Test-Path "$obsPath\cmake\common\obs-modules.cmake") {
          Write-Host "obs-modules.cmake found!"
        } else {
          Write-Host "ERROR: obs-modules.cmake NOT found!"
        }
        cd plugin
        mkdir build
        cd build
        cmake -G "Visual Studio 17 2022" -A x64 -DCMAKE_PREFIX_PATH="${{github.workspace}}/obs-deps;${{github.workspace}}/obs-deps/bin" -DOBS_SOURCE_DIR="${{github.workspace}}/obs-studio" ..
      shell: pwsh

    - name: Build LiveDelay Plugin
      run: |
        cd plugin/build
        cmake --build . --config RelWithDebInfo

    - name: Package Plugin
      run: |
        mkdir release
        copy plugin\build\RelWithDebInfo\livedelay.dll release\
        copy plugin\data\locale\en-US.ini release\

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: livedelay-windows
        path: release/

    - name: Create Release
      if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
      uses: softprops/action-gh-release@v2
      with:
        tag_name: v1.0.${{ github.run_number }}
        name: LiveDelay v1.0.${{ github.run_number }}
        files: release/*
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
