name: Build LiveDelay Plugin

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
    - name: Checkout plugin code
      uses: actions/checkout@v3
      with:
        path: plugin

    - name: Download OBS Studio Pre-built
      run: |
        $ErrorActionPreference = "Stop"
        Write-Host "Downloading pre-built OBS Studio..."
        # Download OBS 30.0.0 portable zip
        $obsUrl = "https://github.com/obsproject/obs-studio/releases/download/30.0.0/OBS-Studio-30.0.0-Windows.zip"
        Invoke-WebRequest -Uri $obsUrl -OutFile "obs.zip"
        Write-Host "Extracting OBS..."
        Expand-Archive -Path "obs.zip" -DestinationPath "${{github.workspace}}/obs-portable"
        Write-Host "OBS extracted successfully"
      shell: pwsh

    - name: Download OBS Development Files
      run: |
        $ErrorActionPreference = "Stop"
        Write-Host "Downloading OBS development files..."
        # Download obs-deps for headers
        $depsUrl = "https://github.com/obsproject/obs-studio/releases/download/30.0.0/obs-studio-30.0.0-windows-x64-debug.zip"
        Invoke-WebRequest -Uri $depsUrl -OutFile "obs-dev.zip"
        Expand-Archive -Path "obs-dev.zip" -DestinationPath "${{github.workspace}}/obs-dev"
        Write-Host "Development files extracted"
      shell: pwsh

    - name: Setup Qt
      uses: jurplel/install-qt-action@v3
      with:
        version: '6.5.0'
        arch: 'win64_msvc2019_64'

    - name: Setup MSVC
      uses: ilammy/msvc-dev-cmd@v1

    - name: Build Plugin
      run: |
        # Create a simple build without CMake
        cd plugin/src

        # Compile plugin sources
        cl.exe /LD /MD /O2 /I"${{github.workspace}}/obs-dev/include" /I"$env:Qt6_DIR/include" /I"$env:Qt6_DIR/include/QtCore" /I"$env:Qt6_DIR/include/QtWidgets" `
          plugin-main.cpp delay-manager.cpp ui-components.cpp `
          /link /OUT:livedelay.dll `
          "${{github.workspace}}/obs-dev/bin/64bit/obs.lib" `
          "${{github.workspace}}/obs-dev/bin/64bit/obs-frontend-api.lib" `
          "$env:Qt6_DIR/lib/Qt6Core.lib" `
          "$env:Qt6_DIR/lib/Qt6Widgets.lib"
      shell: pwsh

    - name: Package Plugin
      run: |
        mkdir release
        copy plugin\src\livedelay.dll release\
        copy plugin\data\locale\en-US.ini release\
      shell: cmd

    - name: Upload Artifact
      uses: actions/upload-artifact@v4
      with:
        name: livedelay-windows
        path: release/

    - name: Create Release
      if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
      uses: softprops/action-gh-release@v2
      with:
        tag_name: v1.0.${{ github.run_number }}
        name: LiveDelay v1.0.${{ github.run_number }}
        files: release/*
        draft: false
        prerelease: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
