name: Build LiveDelay Plugin

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

env:
  PLUGIN_NAME: livedelay

jobs:
  windows-build:
    name: Windows Build
    runs-on: windows-2022

    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          submodules: recursive

      - name: Setup Environment
        run: |
          ## SETUP ENVIRONMENT SCRIPT
          echo "OBS_VERSION=30.0.0" >> $env:GITHUB_ENV

      - name: Build Plugin
        uses: obsproject/obs-plugintemplate/.github/actions/build-plugin@main
        with:
          workingDirectory: ${{ github.workspace }}
          target: ${{ matrix.config.target }}
          config: RelWithDebInfo

      - name: Package Plugin
        run: |
          mkdir release
          Copy-Item "build_x64/rundir/RelWithDebInfo/obs-plugins/64bit/${{ env.PLUGIN_NAME }}.dll" release/
          if (Test-Path "data/locale/en-US.ini") {
            Copy-Item "data/locale/en-US.ini" release/
          }

      - name: Upload Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.PLUGIN_NAME }}-windows
          path: release/

      - name: Create Release
        if: github.ref == 'refs/heads/main' || github.ref == 'refs/heads/master'
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v1.0.${{ github.run_number }}
          name: LiveDelay v1.0.${{ github.run_number }}
          files: release/*
          draft: false
          prerelease: false
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    strategy:
      matrix:
        config:
          - { target: x64, arch: x64 }
